## TODO .env Config wird noch nicht in der Nest anwendung geladen, ich habe so was schon mal gebaut, das muss noch rüber kopiert werden 

version: "3.8"

services:

  frontend:
    build: ./site
    image: de.climactivity.frontend:0.1.0
    restart: always
    volumes:
      - ./log_frontend:/var/log/nginx
      - ./img:/var/img
    networks:
      - main
    depends_on:
      - backend
    ports:
      - 8080:80
    environment: 
      LOCALIZATION_LINK: ${LOCALIZATION_LINK}
     env_file:
       - .env
    

  backend:
    build: ./server
    image: de.climactivity.backend:0.1.0
    restart: always
    volumes:
      - ./log_backend:/var/log
      - ./img:/var/img
    links:
      - db
    networks:
      - main
    depends_on:
      - db
    environment:
      SERVE_STATIC: "false"
      DB_HOST: db
      DB_PORT: 27017
      IMG_DIR: /var/img
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DATABASE: ${MONGO_INITDB_DATABASE}
#    env_file: 
#      - .env

  db: 
    image: bitnami/mongodb:latest
    restart: always
#    env_file:
#      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DATABASE: ${MONGO_INITDB_DATABASE}
#    ports:
#      - 27017:27017
    volumes:
      # named volumes
      - mongoconfig:/data/configdb
      - ./mongodb_data_container:/data/db
      - ./mongoshell:/home/mongodb/
    networks:
      - main

volumes:
  mongoconfig: {}
  mongoshell: {}
  
networks:
  main:
    driver: bridge